name: input_tracker
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter  
  sqflite: ^2.4.2
  path: ^1.9.0
  crypto: ^3.0.3
  go_router: ^14.2.0
  sqflite_common_ffi: ^2.3.7
  sqflite_common_ffi_web: ^1.1.1
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  local_auth: ^2.3.0
  window_manager: ^0.5.1
  flutter_launcher_icons: ^0.14.4
  excel: ^4.0.6
  path_provider: ^2.1.5
  open_file_plus: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png" # Path ke gambar Anda
  min_sdk_android: 21 # Opsional
  adaptive_icon_background: "#ffffff" # Warna background (untuk Android Adaptive Icon)
  adaptive_icon_foreground: "assets/images/icon.png" # Gambar foreground
  windwos: 
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 48

